openapi: 3.0.1
info:
  title: YT Caption Retriever
  description: A plugin that retrieves captions from YouTube videos.
  version: '1'
servers:
  - url: https://yt-caption-retriever.onrender.com
paths:
  /captions:
    post:
      operationId: fetchCaptions
      summary: Get the captions for a YouTube video in various languages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                video_id:
                  type: string
                  description: The unique identifier for the YouTube video
                format:
                  type: string
                  description: The format to return the captions in ('srt' or 'text')
                  default: 'text'
                  enum:
                    - srt
                    - text
                type:
                  type: string
                  description: The type of transcript to fetch ('auto' or 'manual')
                  default: 'manual'
                  enum:
                    - auto
                    - manual
                lang:
                  type: string
                  description: The language code for the captions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fetchCaptionsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /available_languages:
    get:
      operationId: fetchAvailableLanguages
      summary: Get the available languages for a YouTube video's captions
      parameters:
        - name: video_id
          in: query
          description: The unique identifier for the YouTube video
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fetchAvailableLanguagesResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    fetchCaptionsResponse:
      type: object
      properties:
        captions:
          type: string
          description: The captions of the YouTube video in the requested format
    fetchAvailableLanguagesResponse:
      type: object
      properties:
        available_languages:
          type: array
          items:
            type: string
          description: The available languages for the YouTube video's captions
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: An error message describing the issue
